BaseBundle:
    resource: "@UtegBaseBundle/Controller"
    type:     annotation

ModLoader:
    resource: init
    type:     module

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"