uteg_judging_topic:
    channel: uteg/judging/{comp_id}
    handler:
        callback: 'uteg.judgingTopic' #related to the getName() of your topic
    requirements:
        comp_id:
            pattern: "\d+" #accept all valid regex, don't put delimiters !