uteg_topic:
    channel: judging/topic/{compid}/{competitionPlace}
    handler:
        callback: 'uteg.topic.judging'
    requirements:
        compid:
            pattern: "\d+"
        competitionPlace:
            pattern: "\d+"